mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 44.192.18.124   # default: localhost
    port: 1883  # default: 1883
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong
  # file_output_py
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /file_output_py
    topic_to: file_output_py
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: file_output_py
    topic_to: /file_output_back
  # joint_state_desired
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: /joint_state_desired
    topic_to: joint_state_desired
  # joint_state_actual
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: /joint_state_actual
    topic_to: joint_state_actual
  # joint_state_error
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: /joint_state_error
    topic_to: joint_state_error
  # timestamp
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /timestamp
    topic_to: timestamp
  # activate
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: activate
    topic_to: /activate
