mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 3.239.10.202   # default: localhost
    port: 1883  # default: 1883
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong
  # file_output_py
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /file_output_py
    topic_to: file_output_py
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: file_output_py
    topic_to: /file_output_back
  # joint_state_desired
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: /joint_state_desired
    topic_to: joint_state_desired
  # joint_state_actual
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: /joint_state_actual
    topic_to: joint_state_actual
  # joint_state_error
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Float64MultiArray
    topic_from: /joint_state_error
    topic_to: joint_state_error
  # joint_state_feedback
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: control_msgs.msg:FollowJointTrajectoryFeedback
    topic_from: /joint_state_feedback
    topic_to: joint_state_feedback
  # timestamp
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /timestamp
    topic_to: timestamp
  # ft_sensor
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: geometry_msgs.msg:WrenchStamped
    topic_from: /ft_sensor
    topic_to: ft_sensor
  # activate
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: activate
    topic_to: /activate
  # ask_supervisor
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: ask_supervisor
    topic_to: /ask_supervisor
  # supervisor_reply
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /supervisor_reply
    topic_to: supervisor_reply
